"""create incidents tables

Revision ID: 7770350f4d95
Revises: a458d2082490
Create Date: 2026-09-28 12:49:58.928766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7770350f4d95'
down_revision: Union[str, Sequence[str], None] = 'a458d2082490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('malware', 'phishing', 'unauthorized_access', 'data_breach', 'denial_of_service', 'misconfiguration', 'other', name='incidentcategory', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', name='priority', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'mitigated', 'resolved', 'closed', name='incidentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('incident_assets',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_incident_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_assets_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'asset_id', name=op.f('pk_incident_assets'))
    )
    op.create_table('incident_vulnerabilities',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_vulnerabilities_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('fk_incident_vulnerabilities_vulnerability_id_vulnerabilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'vulnerability_id', name=op.f('pk_incident_vulnerabilities'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_vulnerabilities')
    op.drop_table('incident_assets')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
