"""add role to users

Revision ID: 8f95ef39467d
Revises: 313cfa458f59
Create Date: 2026-09-28 14:22:44.895168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f95ef39467d'
down_revision: Union[str, Sequence[str], None] = '313cfa458f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('analyst', 'admin', name='userrole', native_enum=False, length=32), server_default='analyst', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
