"""create incident status history table

Revision ID: 873e1dbbf2d3
Revises: 7770350f4d95
Create Date: 2026-09-28 12:50:26.152843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873e1dbbf2d3'
down_revision: Union[str, Sequence[str], None] = '7770350f4d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('open', 'investigating', 'mitigated', 'resolved', 'closed', name='incidentstatus', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('open', 'investigating', 'mitigated', 'resolved', 'closed', name='incidentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_status_history_incident_id_incidents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_status_history'))
    )
    op.create_index(op.f('ix_incident_status_history_incident_id'), 'incident_status_history', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_status_history_incident_id'), table_name='incident_status_history')
    op.drop_table('incident_status_history')
    # ### end Alembic commands ###
