"""create login attempts table

Revision ID: 313cfa458f59
Revises: ba46ba5248ed
Create Date: 2026-09-28 14:20:47.451443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313cfa458f59'
down_revision: Union[str, Sequence[str], None] = 'ba46ba5248ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_email_attempted_at', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('ix_login_attempts_ip_address_attempted_at', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_ip_address_attempted_at', table_name='login_attempts')
    op.drop_index('ix_login_attempts_email_attempted_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
