"""create assets table

Revision ID: 8b0ca344b6e9
Revises: 
Create Date: 2026-09-28 12:48:15.548214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0ca344b6e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.Enum('server', 'workstation', 'network_device', 'application', 'database', 'cloud_service', 'other', name='assettype', native_enum=False, length=32), nullable=False),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='criticality', native_enum=False, length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
